# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: test-timefilter
  path.config: "/usr/share/logstash/pipeline/logstash-kafka.conf"
  pipeline.workers: 1
- pipeline.id: test
  path.config: "/usr/share/logstash/pipeline/logstash-test.conf"
  pipeline.workers: 1

